services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "2019:2019"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - brimble-net

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CADDY_URL=http://caddy:2019
    depends_on:
      - caddy
    networks:
      - brimble-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - brimble-net

networks:
  brimble-net:
    driver: bridge
